### ISSUE TITLE
console listener

### ISSUE THREAD

**Issue by lampaa** [SpazeDog/rootfw#1]
Hi!

Trying to make reading from console: `getevent /dev/input/event1` (touch event), but the flow is continuously. How do I add an event handler emergence of a new line in the console?

**Comment by dbergloev** [comment]
Well that would require a consistent reader that execute a callback on each new input. Not really supported in RootFW, but it sounds like a good idea for it. Will have a look at that and see if that could be easily added.

**Comment by lampaa** [comment]
@dk-zero-cool You have not done this function? The project is stand still :(

**Comment by dbergloev** [comment]
It is not still, but I am not pushing anything to github until it works. And I have not had much time to look at it yet, I have had exams and other school stuff to take care of, and it is soon Christmas, which also must be planned. I will upload something ones I have it ready.

**Comment by lampaa** [comment]
Hi, @dk-zero-cool!
I add listener as handler: 

``` java
/**
 * callback
 */
Handler handler = new Handler() {
    @Override
    public void handleMessage(Message msg) {
        Bundle bundle = msg.getData();
        String line = bundle.getString("line");

        Toast.makeText(context, "line: " + line, Toast.LENGTH_LONG).show();
    }
};

RootFW root = new RootFW();

if ( root.connect() ) {
    root.shell().callrun("command1", handler);
    //root.disconnect();
}
```

https://github.com/lampaa/rootfw/blob/3_gen/src/com/spazedog/lib/rootfw3/extenders/ShellExtender.java#L210

**Comment by dbergloev** [comment]
Not bad. 

However I have been meaning to rebuild the core of this library for some time, and since the current structure did not support a proper way of doing this (Even though yours is a good attempt of implementation), I decided to create a new base. 

You can checkout the RootRW4 (4_gen branch) to see it. I still need to convert all of the 3_gen extenders to it, but the base works and supports different types of shell operations, incl. your monitor request.
